spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=product-management;encrypt=false
    username: alten
    password: alten
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  jwt:
    secret-key: alten-secret-key
