spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=product;integratedSecurity=true
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
